In [2]:
import pandas as pd
import numpy as np

In [3]:
my_series = [3, 4, 56, 6, 6]
my_index = ["a", "b", "c", "d", "e"]

my_pd_series2 = pd.Series(my_series, index=my_index)
my_pd_series2

a     3
b     4
c    56
d     6
e     6
dtype: int64

In [4]:
#Key value dictionary
cars = {"Alpha Romeo": 12, "BMW":22, "Cadilac":2, "Datson":12, "Ferrari":4}
my_cars = pd.Series(cars)
my_cars

Alpha Romeo    12
BMW            22
Cadilac         2
Datson         12
Ferrari         4
dtype: int64

In [5]:
from numpy.random import randn
my_data = randn(4,3)     # 4 rows, 3 columns
my_rows = ["A", "B", "C", "D"]
my_cols = ["Mon", "Tue", "Wed"]

In [6]:
# Create dataframe
my_df = pd.DataFrame(my_data, my_rows, my_cols)
my_df

        Mon       Tue       Wed
A -0.413583 -0.953778 -0.956455
B -0.153887  1.022883  1.092144
C  1.421601  0.793412  0.655330
D  0.238031  0.953542 -0.864270

In [7]:
import csv

# Define the data
data = [
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
        {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "New Hampshire"},
    {"Name": "Jonathan", "Age": 43, "City": "New Delhi"},
    {"Name": "Don", "Age": 39, "City": "Naples"},
    {"Name": "Vohn", "Age": 67, "City": "Nairobi"},
    {"Name": "John", "Age": 30, "City": "New York"},
    {"Name": "Alice", "Age": 25, "City": "Los Angeles"},
    {"Name": "Bob", "Age": 35, "City": "Chicago"},
    {"Name": "Emma", "Age": 28, "City": "Houston"},
    {"Name": "Michael", "Age": 40, "City": "Miami"},
    {"Name": "Jon", "Age": 33, "City": "Yorkshire"},
    {"Name": "Joe", "Age": 35, "City": "Rampur Garden"},
    {"Name": "Jonathan", "Age": 43, "City": "Subhash Nagar"},
    {"Name": "Don", "Age": 39, "City": "Dhopa"},
    {"Name": "Vohn", "Age": 67, "City": "Sadar"},
    {"Name": "John", "Age": 30, "City": "Cantt"},
    {"Name": "Alice", "Age": 25, "City": "Kutubkhana"},
    {"Name": "Bob", "Age": 35, "City": "Kohadapeer"},
    {"Name": "Emma", "Age": 28, "City": "Madinath"},
    {"Name": "Michael", "Age": 40, "City": "Kareli"},
    {"Name": "Jon", "Age": 33, "City": "Kargaina"},
    {"Name": "Joe", "Age": 35, "City": "Bareilly"},
    {"Name": "Jonathan", "Age": 43, "City": "Nainital"},
    {"Name": "Don", "Age": 39, "City": "Manali"},
    {"Name": "Vohn", "Age": 67, "City": "Dhaarchula"}
]

# Define the file path
csv_file_path = "example.csv"

# Define the field names (column names)
fieldnames = ["Name", "Age", "City"]

# Write data to CSV file
with open(csv_file_path, mode='w', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=fieldnames)

    # Write header
    writer.writeheader()

    # Write rows
    for row in data:
        writer.writerow(row)

print(f"CSV file '{csv_file_path}' has been created successfully.")

CSV file 'example.csv' has been created successfully.

In [8]:
# Import the csv file
my_df2 = pd.read_csv('example.csv')
my_df2.tail(6)

          Name  Age        City
2554   Michael   40      Kareli
2555       Jon   33    Kargaina
2556       Joe   35    Bareilly
2557  Jonathan   43    Nainital
2558       Don   39      Manali
2559      Vohn   67  Dhaarchula

In [9]:
my_df2.loc[2]

Name        Bob
Age          35
City    Chicago
Name: 2, dtype: object

In [10]:
my_df2.loc[[3,5]]

   Name  Age       City
3  Emma   28    Houston
5   Jon   33  Yorkshire

In [11]:
my_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2560 entries, 0 to 2559
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2560 non-null   object
 1   Age     2560 non-null   int64
 2   City    2560 non-null   object
dtypes: int64(1), object(2)
memory usage: 60.1+ KB

In [13]:
my_df2['City'].describe()

count         2560
unique          24
top       New York
freq           255
Name: City, dtype: object

In [14]:
my_df2.iloc[:,0]

0           John
1          Alice
2            Bob
3           Emma
4        Michael
          ...
2555         Jon
2556         Joe
2557    Jonathan
2558         Don
2559        Vohn
Name: Name, Length: 2560, dtype: object

In [15]:
my_df2['Name']

0           John
1          Alice
2            Bob
3           Emma
4        Michael
          ...
2555         Jon
2556         Joe
2557    Jonathan
2558         Don
2559        Vohn
Name: Name, Length: 2560, dtype: object

In [16]:
my_df2.Name

0           John
1          Alice
2            Bob
3           Emma
4        Michael
          ...
2555         Jon
2556         Joe
2557    Jonathan
2558         Don
2559        Vohn
Name: Name, Length: 2560, dtype: object

In [17]:
# Count data
my_df2['City'].value_counts()

City
New York         255
Chicago          255
Houston          255
Miami            255
Yorkshire        255
Los Angeles      255
New Hampshire    254
New Delhi        254
Naples           254
Nairobi          254
Madinath           1
Manali             1
Nainital           1
Bareilly           1
Kargaina           1
Kareli             1
Dhopa              1
Kohadapeer         1
Kutubkhana         1
Cantt              1
Sadar              1
Subhash Nagar      1
Rampur Garden      1
Dhaarchula         1
Name: count, dtype: int64

In [18]:
# Count data, Ascending order
my_df2['City'].value_counts(ascending = True)

City
Subhash Nagar      1
Nainital           1
Bareilly           1
Kargaina           1
Kareli             1
Madinath           1
Kohadapeer         1
Kutubkhana         1
Cantt              1
Sadar              1
Dhopa              1
Dhaarchula         1
Rampur Garden      1
Manali             1
Nairobi          254
Naples           254
New Delhi        254
New Hampshire    254
Yorkshire        255
Miami            255
Houston          255
Chicago          255
Los Angeles      255
New York         255
Name: count, dtype: int64

In [19]:
#Count data, including Not available values too
my_df2['City'].value_counts(dropna=False)

City
New York         255
Chicago          255
Houston          255
Miami            255
Yorkshire        255
Los Angeles      255
New Hampshire    254
New Delhi        254
Naples           254
Nairobi          254
Madinath           1
Manali             1
Nainital           1
Bareilly           1
Kargaina           1
Kareli             1
Dhopa              1
Kohadapeer         1
Kutubkhana         1
Cantt              1
Sadar              1
Subhash Nagar      1
Rampur Garden      1
Dhaarchula         1
Name: count, dtype: int64

In [ ]:
# Relative frequency %
my_df2['Age'].value_counts(normalize=True)

Age
35    0.2
30    0.1
25    0.1
28    0.1
40    0.1
33    0.1
43    0.1
39    0.1
67    0.1
Name: proportion, dtype: float64

In [ ]:
# Count specific item count
my_df2['City'].value_counts()['Bareilly']

1

In [ ]:
#Count unique values- Size
my_df2.groupby('City').size()

City
Bareilly           1
Cantt              1
Chicago          255
Dhaarchula         1
Dhopa              1
Houston          255
Kareli             1
Kargaina           1
Kohadapeer         1
Kutubkhana         1
Los Angeles      255
Madinath           1
Manali             1
Miami            255
Nainital           1
Nairobi          254
Naples           254
New Delhi        254
New Hampshire    254
New York         255
Rampur Garden      1
Sadar              1
Subhash Nagar      1
Yorkshire        255
dtype: int64

In [ ]:
#Count unique values- COunt
my_df2.groupby('City').count()

               Name  Age
City
Bareilly          1    1
Cantt             1    1
Chicago         255  255
Dhaarchula        1    1
Dhopa             1    1
Houston         255  255
Kareli            1    1
Kargaina          1    1
Kohadapeer        1    1
Kutubkhana        1    1
Los Angeles     255  255
Madinath          1    1
Manali            1    1
Miami           255  255
Nainital          1    1
Nairobi         254  254
Naples          254  254
New Delhi       254  254
New Hampshire   254  254
New York        255  255
Rampur Garden     1    1
Sadar             1    1
Subhash Nagar     1    1
Yorkshire       255  255

In [ ]:
my_df2.apply(pd.value_counts)

                Name    Age   City
Alice          256.0    NaN    NaN
Bob            256.0    NaN    NaN
Don            256.0    NaN    NaN
Emma           256.0    NaN    NaN
Joe            256.0    NaN    NaN
John           256.0    NaN    NaN
Jon            256.0    NaN    NaN
Jonathan       256.0    NaN    NaN
Michael        256.0    NaN    NaN
Vohn           256.0    NaN    NaN
35               NaN  512.0    NaN
30               NaN  256.0    NaN
25               NaN  256.0    NaN
28               NaN  256.0    NaN
40               NaN  256.0    NaN
33               NaN  256.0    NaN
43               NaN  256.0    NaN
39               NaN  256.0    NaN
67               NaN  256.0    NaN
New York         NaN    NaN  255.0
Chicago          NaN    NaN  255.0
Houston          NaN    NaN  255.0
Miami            NaN    NaN  255.0
Yorkshire        NaN    NaN  255.0
Los Angeles      NaN    NaN  255.0
New Hampshire    NaN    NaN  254.0
New Delhi        NaN    NaN  254.0
Naples           NaN    NaN  254.0
Nairobi          NaN    NaN  254.0
Madinath         NaN    NaN    1.0
Manali           NaN    NaN    1.0
Nainital         NaN    NaN    1.0
Bareilly         NaN    NaN    1.0
Kargaina         NaN    NaN    1.0
Kareli           NaN    NaN    1.0
Dhopa            NaN    NaN    1.0
Kohadapeer       NaN    NaN    1.0
Kutubkhana       NaN    NaN    1.0
Cantt            NaN    NaN    1.0
Sadar            NaN    NaN    1.0
Subhash Nagar    NaN    NaN    1.0
Rampur Garden    NaN    NaN    1.0
Dhaarchula       NaN    NaN    1.0

In [20]:
# Add new columns to dataframes
#my_df2["Alive/Dead"] = ["Yes!"]*len(my_df2)
my_df2["Alive/Dead"] = [True]*len(my_df2)
my_df2

          Name  Age         City  Alive/Dead
0         John   30     New York        True
1        Alice   25  Los Angeles        True
2          Bob   35      Chicago        True
3         Emma   28      Houston        True
4      Michael   40        Miami        True
...        ...  ...          ...         ...
2555       Jon   33     Kargaina        True
2556       Joe   35     Bareilly        True
2557  Jonathan   43     Nainital        True
2558       Don   39       Manali        True
2559      Vohn   67   Dhaarchula        True

[2560 rows x 4 columns]

In [21]:
# We want to create a column, but the dont know the exact value--> Add Nan value
my_df2["US citizen"] = [np.nan]*len(my_df2)
my_df2

          Name  Age         City  Alive/Dead  US citizen
0         John   30     New York        True         NaN
1        Alice   25  Los Angeles        True         NaN
2          Bob   35      Chicago        True         NaN
3         Emma   28      Houston        True         NaN
4      Michael   40        Miami        True         NaN
...        ...  ...          ...         ...         ...
2555       Jon   33     Kargaina        True         NaN
2556       Joe   35     Bareilly        True         NaN
2557  Jonathan   43     Nainital        True         NaN
2558       Don   39       Manali        True         NaN
2559      Vohn   67   Dhaarchula        True         NaN

[2560 rows x 5 columns]

In [22]:
# Adding a column at a particular location
my_df2.insert(3, "Living in USA", [True]*len(my_df2))
my_df2

          Name  Age         City  Living in USA  Alive/Dead  US citizen
0         John   30     New York           True        True         NaN
1        Alice   25  Los Angeles           True        True         NaN
2          Bob   35      Chicago           True        True         NaN
3         Emma   28      Houston           True        True         NaN
4      Michael   40        Miami           True        True         NaN
...        ...  ...          ...            ...         ...         ...
2555       Jon   33     Kargaina           True        True         NaN
2556       Joe   35     Bareilly           True        True         NaN
2557  Jonathan   43     Nainital           True        True         NaN
2558       Don   39       Manali           True        True         NaN
2559      Vohn   67   Dhaarchula           True        True         NaN

[2560 rows x 6 columns]

In [23]:
# Add a new dataframe by creating a new df
my_df3 = my_df2.assign(Dead=["No"]*len(my_df2))
my_df3

          Name  Age         City  Living in USA  Alive/Dead  US citizen Dead
0         John   30     New York           True        True         NaN   No
1        Alice   25  Los Angeles           True        True         NaN   No
2          Bob   35      Chicago           True        True         NaN   No
3         Emma   28      Houston           True        True         NaN   No
4      Michael   40        Miami           True        True         NaN   No
...        ...  ...          ...            ...         ...         ...  ...
2555       Jon   33     Kargaina           True        True         NaN   No
2556       Joe   35     Bareilly           True        True         NaN   No
2557  Jonathan   43     Nainital           True        True         NaN   No
2558       Don   39       Manali           True        True         NaN   No
2559      Vohn   67   Dhaarchula           True        True         NaN   No

[2560 rows x 7 columns]

In [ ]:
# Remove columns
my_df3.drop("Alive/Dead", axis=1, inplace=True)   #Rows-->Axis=0   Columns-->Axis=1 # inplace=True --> permanent delete
my_df3

In [ ]:
# Remove row
my_df3.drop(3, axis=0, inplace=True)
my_df3

          Name  Age         City  Living in USA Dead
0         John   30     New York           True   No
1        Alice   25  Los Angeles           True   No
2          Bob   35      Chicago           True   No
4      Michael   40        Miami           True   No
5          Jon   33    Yorkshire           True   No
...        ...  ...          ...            ...  ...
2555       Jon   33     Kargaina           True   No
2556       Joe   35     Bareilly           True   No
2557  Jonathan   43     Nainital           True   No
2558       Don   39       Manali           True   No
2559      Vohn   67   Dhaarchula           True   No

[2559 rows x 5 columns]

In [ ]:
#Grab the info in any particular row
my_df3.loc[2]          # we are using the index number of the row

Name                 Bob
Age                   35
City             Chicago
Living in USA       True
Dead                  No
Name: 2, dtype: object

In [ ]:
my_df3.iloc[4]

Name                   Jon
Age                     33
City             Yorkshire
Living in USA         True
Dead                    No
Name: 5, dtype: object

In [ ]:
my_df3.loc[4, "Living in USA"]      # Retrieve a particular value, pass the row# and column name

True

In [ ]:
#Grab a subset
my_df3.loc[[1, 1],["Name","Living in USA"]]        # [[row1, row2], [column1, column2]]

    Name  Living in USA
1  Alice           True
1  Alice           True

In [ ]:
# Conditional selection
my_df3 == 35

       Name    Age   City  Living in USA   Dead
0     False  False  False          False  False
1     False  False  False          False  False
2     False   True  False          False  False
4     False  False  False          False  False
5     False  False  False          False  False
...     ...    ...    ...            ...    ...
2555  False  False  False          False  False
2556  False   True  False          False  False
2557  False  False  False          False  False
2558  False  False  False          False  False
2559  False  False  False          False  False

[2559 rows x 5 columns]

In [ ]:
my_df3 == "Jon"

In [ ]:
my_df3[my_df3 == "Dhaarchula"]

In [ ]:
#Grab only the column which has that value
#my_df3.loc[my_df3["Age"] <= 31,"Name"]
#my_df3.loc[my_df3["Age"] == 31,"Name"]
#my_df3.loc[my_df3["Age"] <= 31,"Name"]
my_df3.loc[my_df3["Age"] >= 59,"Name"]

9       Vohn
19      Vohn
29      Vohn
39      Vohn
49      Vohn
        ...
2519    Vohn
2529    Vohn
2539    Vohn
2549    Vohn
2559    Vohn
Name: Name, Length: 256, dtype: object

In [24]:
# Multiple conditional statements--> and
my_df3[(my_df3["Age"] >= 30) & (my_df3["Living in USA"] == True) & (my_df3["Dead"] == "No")]

          Name  Age           City  Living in USA  Alive/Dead  US citizen Dead
0         John   30       New York           True        True         NaN   No
2          Bob   35        Chicago           True        True         NaN   No
4      Michael   40          Miami           True        True         NaN   No
5          Jon   33      Yorkshire           True        True         NaN   No
6          Joe   35  New Hampshire           True        True         NaN   No
...        ...  ...            ...            ...         ...         ...  ...
2555       Jon   33       Kargaina           True        True         NaN   No
2556       Joe   35       Bareilly           True        True         NaN   No
2557  Jonathan   43       Nainital           True        True         NaN   No
2558       Don   39         Manali           True        True         NaN   No
2559      Vohn   67     Dhaarchula           True        True         NaN   No

[2048 rows x 7 columns]

In [25]:
# or condition
my_df3[(my_df3["Age"] == 40) | (my_df3["Living in USA"] == False) | (my_df3["Dead"] == "Yes")]

         Name  Age    City  Living in USA  Alive/Dead  US citizen Dead
4     Michael   40   Miami           True        True         NaN   No
14    Michael   40   Miami           True        True         NaN   No
24    Michael   40   Miami           True        True         NaN   No
34    Michael   40   Miami           True        True         NaN   No
44    Michael   40   Miami           True        True         NaN   No
...       ...  ...     ...            ...         ...         ...  ...
2514  Michael   40   Miami           True        True         NaN   No
2524  Michael   40   Miami           True        True         NaN   No
2534  Michael   40   Miami           True        True         NaN   No
2544  Michael   40   Miami           True        True         NaN   No
2554  Michael   40  Kareli           True        True         NaN   No

[256 rows x 7 columns]

In [26]:
# Specific value required

my_df3[(my_df3["Age"] >= 50) & (my_df3["Living in USA"] == True) & (my_df3["Dead"] == "No")]["Name"]

9       Vohn
19      Vohn
29      Vohn
39      Vohn
49      Vohn
        ...
2519    Vohn
2529    Vohn
2539    Vohn
2549    Vohn
2559    Vohn
Name: Name, Length: 256, dtype: object

In [57]:
# Dealing with incomplete data
lululu = {'A':[np.nan,20000,3,], 'B':[2000,np.nan,6000], 'C':[323000,56,76], 'D':[454,42,56500], 'E':[34,4000000,12], 'F':[923000,56,7600] }
my_df4=pd.DataFrame(lululu)
my_df4

         A       B       C      D        E       F
0      NaN  2000.0  323000    454       34  923000
1  20000.0     NaN      56     42  4000000      56
2      3.0  6000.0      76  56500       12    7600

In [36]:
#Drop rows with null data
my_df4.dropna()

     A       B   C      D   E     F
2  3.0  6000.0  76  56500  12  7600

In [37]:
#Drop column with null data
my_df4.dropna(axis=1)

        C      D        E       F
0  323000    454       34  923000
1      56     42  4000000      56
2      76  56500       12    7600

In [51]:
#Drop only rows with more than one null value
my_df4.dropna(thresh=2, axis=1) #Threshhold counts non-null values; B column had only 1 non-null values so its gone

         A       C      D        E       F
0      NaN  323000    454       34  923000
1  20000.0      56     42  4000000      56
2      3.0      76  56500       12    7600

In [54]:
#Replace null values
# my_df4.fillna("lodu")
# my_df4.fillna(0.0005)
my_df4.fillna(9999)

         A       B       C      D        E       F
0   9999.0  9999.0  323000    454       34  923000
1  20000.0  9999.0      56     42  4000000      56
2      3.0  6000.0      76  56500       12    7600

In [59]:
#Use math functions to fill null values
#my_df4.fillna(value=my_df4['B'].mean())
# my_df4.fillna(value=my_df4['B'].sum())
my_df4.fillna(value=my_df4['B'].min())

         A       B       C      D        E       F
0   2000.0  2000.0  323000    454       34  923000
1  20000.0  2000.0      56     42  4000000      56
2      3.0  6000.0      76  56500       12    7600

In [126]:
# Groupby functions
Group={ 'Employer': ['Apple', 'Google', 'Meta', 'Apple', 'Google', 'Meta','Apple', 'Google', 'Meta'],
        'Employee': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
        'Age': [23, 34, 45, 19, 32, 21, 43, 54, 29],
        'Annual salary': [120, 230, 223, 343, 233, 245, 453, 454, 122]
}
my_df5=pd.DataFrame(Group)
my_df5

  Employer Employee  Age  Annual salary
0    Apple        A   23            120
1   Google        B   34            230
2     Meta        C   45            223
3    Apple        D   19            343
4   Google        E   32            233
5     Meta        F   21            245
6    Apple        G   43            453
7   Google        H   54            454
8     Meta        I   29            122

In [62]:
# Groupby employer
corp = my_df5.groupby('Employer')

In [68]:
corp.sum()

Employer
Apple     916
Google    917
Meta      590
Name: Annual salary, dtype: int64

In [64]:
corp.min()

         Employee  Annual salary
Employer
Apple           A            120
Google          B            230
Meta            C            122

In [65]:
corp.max()

         Employee  Annual salary
Employer
Apple           G            453
Google          H            454
Meta            I            245

In [69]:
corp['Annual salary'].std()

Employer
Apple     169.665357
Google    128.469192
Meta       65.592174
Name: Annual salary, dtype: float64

In [70]:
corp['Annual salary'].mean()

Employer
Apple     305.333333
Google    305.666667
Meta      196.666667
Name: Annual salary, dtype: float64

In [72]:
corp['Annual salary'].var()

Employer
Apple     28786.333333
Google    16504.333333
Meta       4302.333333
Name: Annual salary, dtype: float64

In [74]:
corp['Employee'].count()

Employer
Apple     3
Google    3
Meta      3
Name: Employee, dtype: int64

In [76]:
# Counting data
my_df3['Name']

0           John
1          Alice
2            Bob
3           Emma
4        Michael
          ...
2555         Jon
2556         Joe
2557    Jonathan
2558         Don
2559        Vohn
Name: Name, Length: 2560, dtype: object

In [79]:
# Count values
my_df3['Name'].value_counts()

Name
John        256
Alice       256
Bob         256
Emma        256
Michael     256
Jon         256
Joe         256
Jonathan    256
Don         256
Vohn        256
Name: count, dtype: int64

In [80]:
#Pass as dataframe --> Looks nicer and we can do different operations with it
pd.DataFrame(my_df3['Name'].value_counts())

          count
Name
John        256
Alice       256
Bob         256
Emma        256
Michael     256
Jon         256
Joe         256
Jonathan    256
Don         256
Vohn        256

In [84]:
#Grab unique names only
pd.DataFrame(my_df3['Name'].unique())

          0
0      John
1     Alice
2       Bob
3      Emma
4   Michael
5       Jon
6       Joe
7  Jonathan
8       Don
9      Vohn

In [96]:
my_df5

  Employer Employee  Annual salary
0    Apple        A            120
1   Google        B            230
2     Meta        C            223
3    Apple        D            343
4   Google        E            233
5     Meta        F            245
6    Apple        G            453
7   Google        H            454
8     Meta        I            122

In [ ]:
# Apply function--> Helps to apply any function we want
# Create function
def mul1000(x):
  return x*1000

# Apply the function
# my_df5['Annual salary'].apply(mul1000)

#Pass as df
pd.DataFrame(my_df5['Annual salary'].apply(mul1000))

In [101]:
#We can efix the format of the output of the function
def mul1000formatted(x):
  return format(x*1000, ",d")

pd.DataFrame(my_df5['Annual salary'].apply(mul1000formatted))

  Annual salary
0       120,000
1       230,000
2       223,000
3       343,000
4       233,000
5       245,000
6       453,000
7       454,000
8       122,000

In [104]:
# Add name
def name(x):
  if x=="A":
    return "Siddharth"
  else:
    return "Chutiye"

my_df5['Employee'].apply(name)

0    Siddharth
1      Chutiye
2      Chutiye
3      Chutiye
4      Chutiye
5      Chutiye
6      Chutiye
7      Chutiye
8      Chutiye
Name: Employee, dtype: object

In [105]:
# Not defining a function, but using lambda
my_df5['Annual salary'].apply(lambda x: x*1000)

0    120000
1    230000
2    223000
3    343000
4    233000
5    245000
6    453000
7    454000
8    122000
Name: Annual salary, dtype: int64

In [107]:
my_df5['Annual salary'].apply(lambda x: format(x*1000, ",d"))

0    120,000
1    230,000
2    223,000
3    343,000
4    233,000
5    245,000
6    453,000
7    454,000
8    122,000
Name: Annual salary, dtype: object

In [128]:
pd.DataFrame(my_df5['Annual salary'].apply(lambda x: format(x*1000, ",d")))

  Annual salary
0       120,000
1       230,000
2       223,000
3       343,000
4       233,000
5       245,000
6       453,000
7       454,000
8       122,000

In [133]:
# Apply function in multiple columns
my_df5[['Age', 'Annual salary']].apply(mul1000)

     Age  Annual salary
0  23000         120000
1  34000         230000
2  45000         223000
3  19000         343000
4  32000         233000
5  21000         245000
6  43000         453000
7  54000         454000
8  29000         122000

In [134]:
#Sorting and ordering
my_df5.sort_values("Age")   #--> Ascending by default

  Employer Employee  Age  Annual salary
3    Apple        D   19            343
5     Meta        F   21            245
0    Apple        A   23            120
8     Meta        I   29            122
4   Google        E   32            233
1   Google        B   34            230
6    Apple        G   43            453
2     Meta        C   45            223
7   Google        H   54            454

In [138]:
my_df5.sort_values("Annual salary", ascending= False) # to make permanent: inplace= True

  Employer Employee  Age  Annual salary
7   Google        H   54            454
6    Apple        G   43            453
3    Apple        D   19            343
5     Meta        F   21            245
4   Google        E   32            233
1   Google        B   34            230
2     Meta        C   45            223
8     Meta        I   29            122
0    Apple        A   23            120

In [141]:
# Sort strings alphabetically
# my_df5.sort_values("Employer")
my_df5.sort_values("Employer", ascending = False)

  Employer Employee  Age  Annual salary
2     Meta        C   45            223
5     Meta        F   21            245
8     Meta        I   29            122
1   Google        B   34            230
4   Google        E   32            233
7   Google        H   54            454
0    Apple        A   23            120
3    Apple        D   19            343
6    Apple        G   43            453